### ISSUE TITLE
Another Timeformat issue

### ISSUE THREAD

**Issue by mhauk30** [JBGruber/rwhatsapp#17] opened 2020-03-14 19:30 UTC
Hello,
when extracting the whatsapp database and using whatsapp viewer, it seems to save the messages in the following format:

01.04.2015 - 16:00:27; ME: Und funktioniert der Toaster auch? :) Hattest du sonst heute noch Vorlesungen?
01.04.2015 - 16:06:34; he: Ne zum Glück nicht aber recht muss ich mir wirklich anhören😁

which gives the time conversion error when using format = "dd.MM.yyyy - HH:mm:ss". Is there an error from my part?

Great package and thanks for the help!

**Comment by JBGruber** [comment] 2020-03-14 19:51
May I ask where you got this from (Android/iOS; language settings?). 

The problem is the `-` character which usually separates the timestamp and user. In your case that separator is `;`, which I've never seen before.

**Comment by mhauk30** [comment] 2020-03-14 19:58
Android, language setting is german.
I tried replacing all the ";" with "," via notepad search and replace, but still get the same error.

**Comment by JBGruber** [comment] 2020-03-14 20:18
Thanks for letting me know. That's the same setup many of my friends use, and they have no problems, so I'm a bit confused why this happens.

However, it turns out I did have a similar format before and it was easy to add this one as well. Try again, it should work now after updating via `remotes::install_github("JBGruber/rwhatsapp")`.

**Comment by JBGruber** [comment] 2020-03-23 14:31
I'm closing this as it seems to be solved.

**Closed as completed by JBGruber** 2020-03-23 14:31 UTC
